---
- hosts: all
  roles: 
      - common
  tags: common    
     
- hosts: prometheus
  roles:
      - prometheus 
  tags: prometheus    

- hosts: node_exporter
  roles:
      - prometheus-nodeExporter  
  tags: nodeExporter          
