---
- name : be sure ntp is installed
  yum:
    name: ntp
    state: present
  tags: ntp

- name: be sure ntp is configured
  template: 
    src: ntp.conf.j2
    dest: /etc/ntp.conf
  notify:
    - restart ntpd
  tags: ntp

- name: be sure ntpd is running and enabled
  service:
     name: ntpd
     state: started
     enabled: yes
  tags: ntp   

- name: make sure ntpd is synchronised
  shell: ntpstat ; if [ $? -ne 0 ]; then systemctl restart ntpd;fi 
  register: result
  until: result.stdout.find("correct") != -1 
  retries: 5
  delay: 10         